spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/bean_and_brew
spring.datasource.username=postgres
spring.datasource.password=admin

# Εντολή για να δημιουργούνται/ανανεώνονται οι πίνακες αυτόματα
spring.jpa.hibernate.ddl-auto=update

# (Προαιρετικό) Τυπώνει την SQL στο terminal για να βλέπεις τι γίνεται στο παρασκήνιο
spring.jpa.show-sql=true
server.port=8081